### ISSUE TITLE
It's possible doing filter & search in the same time?

### ISSUE THREAD

**Issue by DzunN86** [Ovi/DummyJSON#15]
an expected api `https://dummyjson.com/products/search?q=iphone&categorie=smartphones`

**Comment by Ovi** [comment]
Right now it's not possible to do a search and filter with a single request.

**Comment by Ovi** [comment]
Closing this issue due to being non-active, feel free to re-open if needed.

**Comment by front-refined** [comment]
+1，Without this feature, the demo will have some problems
