### ISSUE TITLE
Todos BUG: id type. CREATE returns number. PUT & PATCH return string

### ISSUE THREAD

**Issue by fabioir** [Ovi/DummyJSON#16]
Hello, I noticed something while using your Todos API.
The type of the id is not consistent in the responses. It is reflected in the docu but seems like a bug to me.

![image](https://user-images.githubusercontent.com/25842672/206200896-4cbcf541-055d-4032-9c81-6ef4310bfdaa.png)

**Comment by Ovi** [comment]
Thank you for pointing out this issue @fabioir 
Seems like the issue exists only when updating the todo. I will deploy a fix for this.
