### ISSUE TITLE
can't Auth endpoint!

### ISSUE THREAD

**Issue by micheal1hany** [Ovi/DummyJSON#17]
when i put the body key-value pairs username and password the response is message with : invalid credentials please check it out.
note: i used the user that in the docs.
![https___dummyjson com_users_add - My Workspace - Google Chrome 13-Jan-23 12_20_34 AM](https://user-images.githubusercontent.com/70167512/212193599-f99b5eee-bedc-4215-a305-ad7a3251ea4e.png)

**Comment by Ovi** [comment]
Hi, this is same as: https://github.com/Ovi/DummyJSON/issues/11
