### ISSUE TITLE
Possibility do disable pagination

### ISSUE THREAD

**Issue by nfp0** [Ovi/DummyJSON#20]
Is it possible to disable pagination?

Currently it's impossible to get, for example, all users on a single call.

**Comment by Ovi** [comment]
@nfp0 it's not possible to disable the pagination but you can use the `limit` param to get all users:
[https://dummyjson.com/users?limit=100](https://dummyjson.com/users?limit=100)

**Comment by nfp0** [comment]
@Ovi The problem with the `limit` param is that it assumes the API will always have a fixed number of users.

A param such as `limit=0` or `limit=max`, would be welcomed.

**Comment by Ovi** [comment]
That's a good idea @nfp0!

**Comment by nfp0** [comment]
Thank you!
