### ISSUE TITLE
{   "message": "Invalid user id 'add'" }

### ISSUE THREAD

**Issue by Balaramjalla** [Ovi/DummyJSON#24]

**Comment by Balaramjalla** [comment]
Not able to add new User  getting this error
{
  "message": "Invalid user id 'add'"
}

**Comment by Ovi** [comment]
Can you paste your code here?

**Comment by Balaramjalla** [comment]
Can we add user to server sir

**Comment by Ovi** [comment]
A user can not be added to the server, but it can be mocked as it was added.
https://dummyjson.com/docs/users/#add

**Comment by kevit-dharmit-lakhani** [comment]
it looks like you are doing a GET request instead of a POST request. please follow the instructions given on the website.

**Comment by Ovi** [comment]
Closing this for now, please reopen it when you provide the code here.
