### ISSUE TITLE
User POST Api successful but record not showing GET all user list.

### ISSUE THREAD

**Issue by Snehal14283** [Ovi/DummyJSON#28]
I worked on DummyJSON. I added the User with POST Api. I got the success status for POST Api. Now I am checking whether my record showing under User list and calling [All User Api](https://dummyjson.com/users) but unable to find my inserted record.

I just added 5 fields to post User API: First Name, Last Name, User Name, Email & Password

**Comment by kevit-dharmit-lakhani** [comment]
Please read the docs carefully. It clearly says "Adding a new user will not add it into the server". the post request only mimics a response of adding a user (given all required fields are provided) but does not actually add it in the database.
