### ISSUE TITLE
New post routes

### ISSUE THREAD

**Issue by HigorMoroni** [Ovi/DummyJSON#30]
Hello devs,

I would like to use this api in some educational projects and for that I realized that some interesting end-points are missing.
Two that I can list initially are: 
1. a GET that returns a list of all post tags;
2. a GET that filters all posts that have the category received as payload.

I have experience with javascript and if you find it interesting, I can implement this functionality and create a pull request.

yours sincerely,
Higor Moroni

**Comment by Ovi** [comment]
Hi @HigorMoroni,

Thank you for your interest and your willingness to contribute.
Please go ahead and implement the functionality, and I would be happy to review your pull request.
Let me know if you need any assistance during the process.

Best regards

**Comment by Ovi** [comment]
Closing this issue due to being non-active, feel free to re-open if needed.
