### ISSUE TITLE
Images server is down

### ISSUE THREAD

**Issue by 94Maksim** [Ovi/DummyJSON#39]
Images server is down. Please fix it

**Comment by Ovi** [comment]
I see product images are working fine for me.
Could you please share more details

**Comment by 94Maksim** [comment]
![err](https://github.com/Ovi/DummyJSON/assets/101658975/0bc260f2-d371-4b2d-a7a9-919a2b250b6e)

**Comment by Ovi** [comment]
Ah, yes @94Maksim, this service is down at the moment. Will update the issue when it goes up again.

**Comment by Ovi** [comment]
Image server is working again, closing this issue.
