### ISSUE TITLE
HTTP 204 Mock failing

### ISSUE THREAD

**Issue by Swizz** [Ovi/DummyJSON#43]
Hi, 

Thanks for bringing us DummyJSON, that's a great tool I use a lot for prototyping. 
Unfortunately I found out that using the 204 HTTP Mock route fail unexpectedly with the following error : 
```
upstream connect error or disconnect/reset before headers. reset reason: protocol error
``` 

I tried to run DummyJSON localy and everything works as intented. 
So, I dont know if it might be an error with Railway itself. But here is a way to reproduce.

![image](https://github.com/Ovi/DummyJSON/assets/1062567/9ef58e16-70f8-47eb-be73-f412bbfb3dc6)

Cheers,

**Comment by Ovi** [comment]
@Swizz thank you for mentioning, it's strange that the issue occurs with HTTPS and not with HTTP, I will investigate this further.

![image](https://github.com/Ovi/DummyJSON/assets/23533420/a30630ec-9e2c-4829-bb66-28f26c61802a)

**Comment by Ovi** [comment]
![image](https://github.com/Ovi/DummyJSON/assets/23533420/282fa6e6-1a9b-4a9b-a317-c1dfb9a4c4f9)

This is causing the issue, will fix this soon.
