### ISSUE TITLE
Pagination isn't working

### ISSUE THREAD

**Issue by ashusnapx** [Ovi/DummyJSON#49]
**GitHub Issue Description:**

**Title: Issue with Localhost API Endpoint Returning Empty Array**

**Description:**
I am currently experiencing an issue with the local development environment when trying to fetch data from the API endpoint `http://localhost:3000/products?skip=5&limit=10`. Strangely, the same request to the remote server `https://dummyjson.com/products?skip=5&limit=10` works perfectly fine.

**Problem:**
- Remote API (https://dummyjson.com/products?skip=5&limit=10): Works as expected, returns valid data.
- Local API (http://localhost:3000/products?skip=5&limit=10): Returns an empty array.

**Steps to Reproduce:**
1. Run the application locally.
2. Make a GET request to `http://localhost:3000/products?skip=5&limit=10`.

**Expected Behavior:**
- The local API should return data similar to the remote API.

**Actual Behavior:**
- The local API returns an empty array.

**Additional Information:**
- Both endpoints use the same parameters (`skip` and `limit`).
- No error messages are displayed.

**Environment:**
- Operating System: MacOS
- Node.js Version: 20

**How to Fix:**
If anyone has encountered this issue or has insights into potential solutions, please share your thoughts on how to resolve this discrepancy between the remote and local API endpoints.

**Comment by Ovi** [comment]
I am still unable to reproduce this issue, is this still reproducible?
