### ISSUE TITLE
`limit` and `skip` support into `/products/category` endpoint.

### ISSUE THREAD

**Issue by mrcego** [Ovi/DummyJSON#50]
First, thanks for this dummy JSON, It's nice to practice and testing some researchs for anything.

But I noticed a lack in the endpoint to get products from a category concerning `limit` and `skip` queries, it always returning just 5 records.

![Captura de pantalla 2024-02-15 a la(s) 9 13 26 p  m](https://github.com/Ovi/DummyJSON/assets/65884507/acd36e2d-b1cc-43a3-bcb7-f3b571b0e731)

No matter if you're passing `https://dummyjson.com/products/category/${category}?limit=10&skip=5` via fetch or axios.

Thanks in advance.

**Comment by krzysztof293** [comment]
https://github.com/Ovi/DummyJSON/issues/50#issue-2137755297
