### ISSUE TITLE
JWT_SECRET to verify token

### ISSUE THREAD

**Issue by DevKoenv** [Ovi/DummyJSON#54]
I was wondering if there is a public jwt secret we can use to verify the returned token got from the dummy auth, as the example states it returns a token:
```json
{
   ...
  "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTUsInVzZXJuYW1lIjoia21pbmNoZWxsZSIsImVtYWlsIjoia21pbmNoZWxsZUBxcS5jb20iLCJmaXJzdE5hbWUiOiJKZWFubmUiLCJsYXN0TmFtZSI6IkhhbHZvcnNvbiIsImdlbmRlciI6ImZlbWFsZSIsImltYWdlIjoiaHR0cHM6Ly9yb2JvaGFzaC5vcmcvYXV0cXVpYXV0LnBuZz9zaXplPTUweDUwJnNldD1zZXQxIiwiaWF0IjoxNjM1NzczOTYyLCJleHAiOjE2MzU3Nzc1NjJ9.n9PQX8w8ocKo0dMCw3g8bKhjB8Wo7f7IONFBDqfxKhs"
}
```

but nowhere on the docs it says a secret to verify the token with, when I looked at the source I found that the secret gets stored in an environment variable, but I was wondering if there maby is a public secret that we can use to verify the tokens?

**Comment by Ovi** [comment]
It's in the `dev.env` file:
https://github.com/Ovi/DummyJSON/blob/master/config/dev.env#L3

**Comment by DevKoenv** [comment]
Ahh thanks, must have looked over it!
