### ISSUE TITLE
unique ids when adding new products

### ISSUE THREAD

**Issue by nuclearfartz** [Ovi/DummyJSON#56]
hi there , i created a website using Dummyjsons products and i am using the addproduct method mentioned in the docs but all new added products have the same id and i tried everything and it didnt work , here is whats showing in the console 

{id: 101, title: 'test', price: '2', thumbnail: '1', description: '1'}
description
: 
"1"
id
: 
101
price
: 
"2"
thumbnail
: 
"1"
title
: 
"test"
[[Prototype]]
: 
Object
App.js:109 Product added successfully!
App.js:113 
{id: 101, title: 'test2', price: '2', thumbnail: '2', description: '2'}
description
: 
"2"
id
: 
101
price
: 
"2"
thumbnail
: 
"2"
title
: 
"test2"
[[Prototype]]
: 
Object

**Comment by Ovi** [comment]
Related https://github.com/Ovi/DummyJSON/issues/28
