### ISSUE TITLE
Images and thumbnail not showing

### ISSUE THREAD

**Issue by edomanuli** [Ovi/DummyJSON#57]
Images and thumbnail stopped showing up on my site, as well as postman.

**Comment by Ovi** [comment]
Can you share any URL here? I see it's working fine.

**Comment by edomanuli** [comment]
http://pharaohz.net/products

**Comment by Ovi** [comment]
Your website is using old image endpoints, the images have been moved to a new endpoint, you can find updated urls in the docs

**Comment by edomanuli** [comment]
Ok thank you
