### ISSUE TITLE
Question: Use of data and or API

### ISSUE THREAD

**Issue by klequis1234** [Ovi/DummyJSON#63]
Hi,

I'm creating a course to put on Udemy for which I'll make some amount (likely small) of money. From what I have read about DummyJSON there is no limit on the usage of the data or API but I thought it best to check. Specifically: Can I download the JSON and use it in my course?

Thank you,
Carl

- PS - sorry, I used my course Github account by accident. I'm a real non-spammy user: https://github.com/klequis

**Comment by Ovi** [comment]
You can use it, no worries, however, I will appreciate a shoutout :wink:
