### ISSUE TITLE
OAuth Refresh token flow

### ISSUE THREAD

**Issue by fuvavi** [Ovi/DummyJSON#67]
## Description

- When I call refresh token API (https://dummyjson.com/auth/refresh) I must provide a valid token. Therefore, I must check if the token is valid every time I access the website. Maybe that is not correct and performance is not well. 

- To improve that problem, you should return a refresh token when calling [Login API](https://dummyjson.com/auth/login)
When the token has expired, we will use a refresh token to get a new valid token.

## Reference
 [OAuth Refresh Token Flow Work](https://cloudentity.com/developers/basics/oauth-grant-types/refresh-token-flow/)

![image](https://github.com/Ovi/DummyJSON/assets/33111017/c1ef0712-dbf4-4a35-be0f-d0f4d2a6759d)

**Comment by AmeerAmjed** [comment]
Issue when use refresh token return Token Expired! if valid token return new token.

**Comment by fuvavi** [comment]
@Ovi Thanks for updating 🚀
