### ISSUE TITLE
Implement Token Validation for Endpoint

### ISSUE THREAD

**Issue by AmeerAmjed** [Ovi/DummyJSON#69]
Add a new feature that includes a token with each endpoint request. This token should be validated, and the response should be tailored to the request. If the token is expired, avoid sending an unauthorized error.

Note: Authentication should not be mandatory for every endpoint; implement this only when an invalid token is provided in the header.

**Comment by Ovi** [comment]
We already have this feature, please see [https://dummyjson.com/auth/RESOURCE](https://dummyjson.com/docs#intro-auth)

You can use `/auth` before any resource to leverage the authentication mechanism.
