### ISSUE TITLE
server is down

### ISSUE THREAD

**Issue by GR33NBR1CK** [Ovi/DummyJSON#73]
server is down, please fix

**Comment by Ovi** [comment]
Is it still?

**Comment by GR33NBR1CK** [comment]
yes the site and api is dead

**Comment by Ovi** [comment]
I just checked and it's working for me, what error are you seeing?

**Comment by Ovi** [comment]
![image](https://github.com/Ovi/DummyJSON/assets/23533420/16c9ea1c-70ba-4fff-b623-33fa5bb6b1a0)

**Comment by GR33NBR1CK** [comment]
I figured out that the site doesn't work with DNSSEC turned on. It may be incorrect DNS configuration or your domain provider doesn't support DNSSEC or something else. I added a static dns entry in /etc/hosts, but I encourage you to investigate this :+1:
