### ISSUE TITLE
Inconsistency between "Set-Cookie" headers and fetch responses

### ISSUE THREAD

**Issue by gokhantaskan** [Ovi/DummyJSON#79]
My code includes the following implementation:

![CleanShot 2024-09-16 at 23 32 37@2x](https://github.com/user-attachments/assets/9eaaf235-d68e-4811-bc8d-93bfb2efc0bf)

The idea is to directly use the "Set-Cookie" headers from the original response inside a Next.js middleware. As you can see in the following screenshot:
- The response uses `token` instead of `accessToken` or vice versa. I guess it's mostly used as a `token` except for the "Set-Cookie" header.
- Even if I used `expiresInMins` as "3," the "Set-Cookie" headers have the same dates.

![CleanShot 2024-09-16 at 23 29 34@2x](https://github.com/user-attachments/assets/bf238516-2edf-4f78-b045-791af87be3aa)

**Comment by Ovi** [comment]
Thank you @gokhantaskan!

Since this could be a breaking change for many users, I will display a warning (banner) on the web before making it. Afterward, we will be using `accessToken` instead of `token`.
