### ISSUE TITLE
Ignore GET params for images from product list

### ISSUE THREAD

**Issue by dszymczuk** [Ovi/DummyJSON#86]
Hi.

I love dummy json in my project. Excellent job!

I want to delay only images instead of the whole rest, so the parameter `?delay=1000` doesn't work for me.

I found a solution called `https://requestly.com/` but the add `?_rq_delayed=true` into the URL.
So this link works:
`https://cdn.dummyjson.com/products/images/mens-shirts/Man%20Plaid%20Shirt/2.png`
But this link doesn't work:
`https://cdn.dummyjson.com/products/images/mens-shirts/Man%20Plaid%20Shirt/2.png?_rq_delayed=true`
I've got 404.

Is it possible to ignore all get params for images?

**Comment by Ovi** [comment]
Thanks, @dszymczuk! This behavior is unexpected, and I’ll work on fixing it as soon as possible.

**Comment by dszymczuk** [comment]
I thought I would try to prepare a fix, but it requires set up a database :(

**Comment by Ovi** [comment]
@dszymczuk this is fixed now.
