### ISSUE TITLE
Login with different user's data

### ISSUE THREAD

**Issue by shubhanshu2000** [Ovi/DummyJSON#9]
### Discussed in https://github.com/Ovi/DummyJSON/discussions/4

<div type='discussions-op-text'>

<sup>Originally posted by **rogerok** August  8, 2022</sup>
Hi, I really enjoy your dummysjon and use it in my pet project. Is there any possibility to get auth token except kminchelle user?
Thanks!</div>

**Comment by Ovi** [comment]
Hi @shubhanshu2000, you can use any user's credentials from https://dummyjson.com/users
All users have a username and password.

Username and passwords: https://dummyjson.com/users?select=username,password
